name: AirJedi
options:
  bundleIdPrefix: com.airjedi
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

targets:
  AirJedi:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.airjedi.notifier
        PRODUCT_NAME: AirJedi Alerts
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
        MACOSX_DEPLOYMENT_TARGET: 14.0
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Resources/Info.plist
        INFOPLIST_KEY_LSUIElement: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O

  AirJediTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: AirJedi
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: 5.9
        MACOSX_DEPLOYMENT_TARGET: 14.0
